
language: ruby
rvm:
 - 2.3.2

services:
 - postgresql

notifications:
  email:
    recipients:
      - runfogcity@gmail.com
    on_success: always
    on_failure: always

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: bundle exec rake test

