development:
  adapter: postgresql
  encoding: unicode
  database: fogcityrun
  pool: 5
  username: maxmetcalfe
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: travis_ci_test
  pool: 5
  username: postgres
  password:
  host: localhost
